version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
 
jobs:
  CI/CD:
    docker:
      - image: "cimg/base:stable"
    steps:
     - node/install:
          install-yarn: true
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      - aws-elastic-beanstalk/setup
      - run:
          name: Front-End Install
          command: |
            yarn run frontend:install
      - run:
          name: Back-End Install
          command: |
            yarn run backend:install
      - run:
          name: Front-End Build
          command: |
            yarn run frontend:build
      - run:
          name: Back-End Build
          command: |
            yarn run backend:build
      - run:
          name: Front-End Deploy 
          command: |
            yarn run frontend:deploy
      - run:
          name: Back-End Deploy 
          command: |
            yarn run backend:deploy